-- MySQL Script generated by MySQL Workbench
-- Mon Jun 21 00:56:44 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SlaytheSpireDatabase
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SlaytheSpireDatabase` ;

-- -----------------------------------------------------
-- Schema SlaytheSpireDatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SlaytheSpireDatabase` DEFAULT CHARACTER SET utf8 ;
USE `SlaytheSpireDatabase` ;

-- -----------------------------------------------------
-- Table `SlaytheSpireDatabase`.`hero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SlaytheSpireDatabase`.`hero` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `hp` INT NOT NULL,
  `flavor_text` VARCHAR(255) NOT NULL,
  `image` VARCHAR(2083) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
DEFAULT COLLATE utf8_general_ci;

-- -----------------------------------------------------
-- Table `SlaytheSpireDatabase`.`card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SlaytheSpireDatabase`.`card` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `cost` INT NOT NULL,
  `reinforcement` INT NOT NULL,
  `class` VARCHAR(45) NOT NULL,
  `dedicated` VARCHAR(45) NOT NULL,
  `type` VARCHAR(10) NOT NULL,
  `effect` VARCHAR(200) NULL,
  `comment` VARCHAR(200) NULL,
  `image` VARCHAR(2083) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
DEFAULT COLLATE utf8_general_ci;

-- -----------------------------------------------------
-- Table `SlaytheSpireDatabase`.`start_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SlaytheSpireDatabase`.`start_card` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `card_id` INT NOT NULL,
  `hero_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `hero_id` (`hero_id` ASC) VISIBLE,
  INDEX `card_id` (`card_id` ASC) VISIBLE,
  CONSTRAINT `hero_id`
    FOREIGN KEY (`hero_id`)
    REFERENCES `SlaytheSpireDatabase`.`hero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `card_id`
    FOREIGN KEY (`card_id`)
    REFERENCES `SlaytheSpireDatabase`.`card` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
DEFAULT COLLATE utf8_general_ci;

-- -----------------------------------------------------
-- Table `SlaytheSpireDatabase`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SlaytheSpireDatabase`.`item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `class` VARCHAR(45) NOT NULL,
  `dedicated` VARCHAR(45) NOT NULL,
  `effect` VARCHAR(200) NULL,
  `comments` VARCHAR(255) NULL,
  `image` VARCHAR(2083) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
DEFAULT COLLATE utf8_general_ci;

-- -----------------------------------------------------
-- Table `SlaytheSpireDatabase`.`start_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SlaytheSpireDatabase`.`start_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `item_id` INT NOT NULL,
  `hero_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `hero_id_idx` (`hero_id` ASC) VISIBLE,
  INDEX `item_id_idx` (`item_id` ASC) VISIBLE,
  CONSTRAINT `hero_id`
    FOREIGN KEY (`hero_id`)
    REFERENCES `SlaytheSpireDatabase`.`hero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `item_id`
    FOREIGN KEY (`item_id`)
    REFERENCES `SlaytheSpireDatabase`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
DEFAULT COLLATE utf8_general_ci;

-- -----------------------------------------------------
-- Table `SlaytheSpireDatabase`.`monster`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SlaytheSpireDatabase`.`monster` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `class` VARCHAR(45) NOT NULL,
  `stage` VARCHAR(10) NOT NULL,
  `hp` VARCHAR(45) NOT NULL,
  `attack` VARCHAR(45) NOT NULL,
  `effect` VARCHAR(255) NULL,
  `image` VARCHAR(2083) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
DEFAULT COLLATE utf8_general_ci;

-- -----------------------------------------------------
-- Table `SlaytheSpireDatabase`.`potion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SlaytheSpireDatabase`.`potion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `class` VARCHAR(45) NOT NULL,
  `dedicated` VARCHAR(45) NOT NULL,
  `effect` VARCHAR(255) NULL,
  `image` VARCHAR(2083) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
DEFAULT COLLATE utf8_general_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- insert data
-- -----------------------------------------------------
INSERT INTO hero (id,name,hp,flavor_text,image) VALUES
(null, '아이언클레드', 80, '아이언클래드의 살아남은 병사입니다.악마의 힘을 사용하기 위해 영혼을 팔았습니다.','./hero/Ironclad.JPG'),
(null, '사일런트', 70, '안개 지대에서 온 치명적인 사냥꾼입니다.단검과 독으로 적들을 박멸합니다.','./hero/Cilent.JPG'),
(null, '디펙트', 75, '자아를 깨달은 전투 자동인형입니다.고대의 기술로 구체를 만들 수 있습니다.','./hero/Defect.JPG'),
(null, '와쳐', 72, '첨탑을 "평가"하기 위하여 찾아온 눈먼 수도사입니다.강림의 경지에 이른 고수입니다.','./hero/Watcher.JPG');

INSERT INTO card (id,name,cost,reinforcement,class,dedicated,type,effect,comments,image) VALUES
(null,),
